services:
  postgres:
    image: postgres:14
    container_name: chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chat-password
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatdb
      DB_USER: postgres
      DB_PASSWORD: chat-password
      AWS_REGION: eu-north-1
      S3_BUCKET_NAME: chat-attachments
      AWS_ACCESS_KEY_ID: AKIAYS2NW3RPUE6BGQ4K
      aws_secret_access_key: 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

    depends_on:
      - postgres

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: chat-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
