services:
  postgres:
    image: postgres:14
    container_name: chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chat-password
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
